# Working with data

## Importing and opening file

In [1]:
import pandas as pd

In [5]:
food_info = pd.read_csv("food_info.csv")
print(type(food_info))

<class 'pandas.core.frame.DataFrame'>

In [13]:
# printing first 5 rows
food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,721.0,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,1080.0,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0

In [14]:
# or 3
food_info.head(3)

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0

In [15]:
# getting info about size
food_info.shape

(8618, 36)

In [18]:
#printing columns
food_info.columns

Index(['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)',
       'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)',
       'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)',
       'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)',
       'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)',
       'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)',
       'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)', 'Vit_D_mcg',
       'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)', 'FA_Mono_(g)', 'FA_Poly_(g)',
       'Cholestrl_(mg)'],
      dtype='object')

## Indexing

The Series object is a core data structure that pandas uses to represent rows and columns. A Series is a labelled collection of values similar to the NumPy vector. The main advantage of Series objects is the ability to utilize non-integer labels. NumPy arrays can only utilize integer labels for indexing.

Pandas utilizes this feature to provide more context when returning a row or a column from a dataframe. For example, when you select a row from a dataframe, instead of just returning the values in that row as a list, pandas returns a Series object that contains the column labels as well as the corresponding values:

While we use bracket notation to access elements in a NumPy array or a standard list, we need to use the pandas method `loc[]` to select rows in a dataframe. The `loc[]` method allows you to select rows by row labels. Recall that when you read a file into a dataframe, pandas uses the row number (or position) as each row's label. Pandas uses zero-indexing, so the first row is at index 0, the second row at index 1, and so on.

In [25]:
# First row of DF
food_info.loc[0]

NDB_No                         1001
Shrt_Desc          BUTTER WITH SALT
Water_(g)                     15.87
Energ_Kcal                      717
Protein_(g)                    0.85
Lipid_Tot_(g)                 81.11
Ash_(g)                        2.11
Carbohydrt_(g)                 0.06
Fiber_TD_(g)                      0
Sugar_Tot_(g)                  0.06
Calcium_(mg)                     24
Iron_(mg)                      0.02
Magnesium_(mg)                    2
Phosphorus_(mg)                  24
Potassium_(mg)                   24
Sodium_(mg)                     643
Zinc_(mg)                      0.09
Copper_(mg)                       0
Manganese_(mg)                    0
Selenium_(mcg)                    1
Vit_C_(mg)                        0
Thiamin_(mg)                  0.005
Riboflavin_(mg)               0.034
Niacin_(mg)                   0.042
Vit_B6_(mg)                   0.003
Vit_B12_(mcg)                  0.17
Vit_A_IU                       2499
Vit_A_RAE                       684
Vit_E_(mg)                     2.32
Vit_D_mcg                       1.5
Vit_D_IU                         60
Vit_K_(mcg)                       7
FA_Sat_(g)                   51.368
FA_Mono_(g)                  21.021
FA_Poly_(g)                   3.043
Cholestrl_(mg)                  215
Name: 0, dtype: object

dtype: object refers to the data type, or dtype, of that Series. The object `dtype` is equivalent to the string type in Python. Pandas borrows from the NumPy type system and contains the following dtypes:

    object - for representing string values.
    int - for representing integer values.
    float - for representing float values.
    datetime - for representing time values.
    bool - for representing Boolean values.

When reading a file into a dataframe, pandas analyzes the values and infers each column's types.

In [21]:
print(food_info.dtypes)

NDB_No               int64
Shrt_Desc           object
Water_(g)          float64
Energ_Kcal           int64
Protein_(g)        float64
Lipid_Tot_(g)      float64
Ash_(g)            float64
Carbohydrt_(g)     float64
Fiber_TD_(g)       float64
Sugar_Tot_(g)      float64
Calcium_(mg)       float64
Iron_(mg)          float64
Magnesium_(mg)     float64
Phosphorus_(mg)    float64
Potassium_(mg)     float64
Sodium_(mg)        float64
Zinc_(mg)          float64
Copper_(mg)        float64
Manganese_(mg)     float64
Selenium_(mcg)     float64
Vit_C_(mg)         float64
Thiamin_(mg)       float64
Riboflavin_(mg)    float64
Niacin_(mg)        float64
Vit_B6_(mg)        float64
Vit_B12_(mcg)      float64
Vit_A_IU           float64
Vit_A_RAE          float64
Vit_E_(mg)         float64
Vit_D_mcg          float64
Vit_D_IU           float64
Vit_K_(mcg)        float64
FA_Sat_(g)         float64
FA_Mono_(g)        float64
FA_Poly_(g)        float64
Cholestrl_(mg)     float64
dtype: object

It is possible to access multiple, one or slice of rows through the `loc[]` method.

In [22]:
# 1 row
food_info.loc[10]

NDB_No                     1011
Shrt_Desc          CHEESE COLBY
Water_(g)                  38.2
Energ_Kcal                  394
Protein_(g)               23.76
Lipid_Tot_(g)             32.11
Ash_(g)                    3.36
Carbohydrt_(g)             2.57
Fiber_TD_(g)                  0
Sugar_Tot_(g)              0.52
Calcium_(mg)                685
Iron_(mg)                  0.76
Magnesium_(mg)               26
Phosphorus_(mg)             457
Potassium_(mg)              127
Sodium_(mg)                 604
Zinc_(mg)                  3.07
Copper_(mg)               0.042
Manganese_(mg)            0.012
Selenium_(mcg)             14.5
Vit_C_(mg)                    0
Thiamin_(mg)              0.015
Riboflavin_(mg)           0.375
Niacin_(mg)               0.093
Vit_B6_(mg)               0.079
Vit_B12_(mcg)              0.83
Vit_A_IU                    994
Vit_A_RAE                   264
Vit_E_(mg)                 0.28
Vit_D_mcg                   0.6
Vit_D_IU                     24
Vit_K_(mcg)                 2.7
FA_Sat_(g)               20.218
FA_Mono_(g)                9.28
FA_Poly_(g)               0.953
Cholestrl_(mg)               95
Name: 10, dtype: object

In [23]:
# slice 5:10 indexes (method includes both start and endindex)
food_info.loc[5:10]

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
5,1006,CHEESE BRIE,48.42,334,20.75,27.68,2.70,0.45,0.0,0.45,...,592.0,174.0,0.24,0.5,20.0,2.3,17.410,8.013,0.826,100.0
6,1007,CHEESE CAMEMBERT,51.80,300,19.80,24.26,3.68,0.46,0.0,0.46,...,820.0,241.0,0.21,0.4,18.0,2.0,15.259,7.023,0.724,72.0
7,1008,CHEESE CARAWAY,39.28,376,25.18,29.20,3.28,3.06,0.0,NaN,...,1054.0,271.0,NaN,NaN,NaN,NaN,18.584,8.275,0.830,93.0
8,1009,CHEESE CHEDDAR,37.10,406,24.04,33.82,3.71,1.33,0.0,0.28,...,994.0,263.0,0.78,0.6,24.0,2.9,19.368,8.428,1.433,102.0
9,1010,CHEESE CHESHIRE,37.65,387,23.37,30.60,3.60,4.78,0.0,NaN,...,985.0,233.0,NaN,NaN,NaN,NaN,19.475,8.671,0.870,103.0
10,1011,CHEESE COLBY,38.20,394,23.76,32.11,3.36,2.57,0.0,0.52,...,994.0,264.0,0.28,0.6,24.0,2.7,20.218,9.280,0.953,95.0

In [27]:
# access only some rows
food_info.loc[[0, 10, 100]]

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0
10,1011,CHEESE COLBY,38.20,394,23.76,32.11,3.36,2.57,0.0,0.52,...,994.0,264.0,0.28,0.6,24.0,2.7,20.218,9.280,0.953,95.0
100,1112,WHEY ACID FLUID,93.42,24,0.76,0.09,0.61,5.12,0.0,5.12,...,7.0,2.0,0.00,NaN,NaN,0.0,0.057,0.025,0.004,1.0

To access a single column, use bracket notation and pass in the column name as a string

In [28]:
food_info["Cholestrl_(mg)"]

0       215.0
1       219.0
2       256.0
3        75.0
4        94.0
5       100.0
6        72.0
7        93.0
8       102.0
9       103.0
10       95.0
11       17.0
12       13.0
13        7.0
14       12.0
15        4.0
16      110.0
17       89.0
18       89.0
19      116.0
20       94.0
21      114.0
22      110.0
23       90.0
24       89.0
25       79.0
26       89.0
27       64.0
28       65.0
29       96.0
        ...
8588      0.0
8589      0.0
8590      0.0
8591      0.0
8592      0.0
8593      0.0
8594      0.0
8595     35.0
8596      0.0
8597     54.0
8598      0.0
8599      0.0
8600      0.0
8601      6.0
8602      0.0
8603      0.0
8604      0.0
8605      0.0
8606      0.0
8607      0.0
8608      0.0
8609      0.0
8610      0.0
8611      0.0
8612     50.0
8613     95.0
8614     41.0
8615      0.0
8616     50.0
8617     50.0
Name: Cholestrl_(mg), dtype: float64

In [29]:
food_info[["Water_(g)", "Energ_Kcal", "Protein_(g)"]]

      Water_(g)  Energ_Kcal  Protein_(g)
0         15.87         717         0.85
1         15.87         717         0.85
2          0.24         876         0.28
3         42.41         353        21.40
4         41.11         371        23.24
5         48.42         334        20.75
6         51.80         300        19.80
7         39.28         376        25.18
8         37.10         406        24.04
9         37.65         387        23.37
10        38.20         394        23.76
11        79.79          98        11.12
12        79.64          97        10.69
13        81.01          72        10.34
14        81.24          81        10.45
15        82.48          72        12.39
16        54.44         342         5.93
17        41.56         357        24.99
18        55.22         264        14.21
19        37.92         389        25.60
20        13.44         466         9.65
21        41.46         356        24.94
22        33.19         413        29.81
23        48.42         327        20.05
24        41.01         373        24.48
25        50.01         300        22.17
26        48.38         318        21.60
27        53.78         254        24.26
28        45.54         301        24.58
29        41.77         368        23.41
...         ...         ...          ...
8588       2.00         389         6.60
8589      76.70          91         1.00
8590      83.10          68         0.30
8591       1.30         465         8.70
8592       5.00         401         7.12
8593       2.80         429        12.60
8594      81.60          73         0.50
8595      59.60         179        28.40
8596      14.50         377         4.40
8597      49.90         280        27.50
8598      21.70         688         0.00
8599       0.00         884         0.00
8600      23.90         279         0.00
8601      55.50         257         4.08
8602       9.00         319        11.30
8603       4.20         356         5.30
8604      84.40          62         0.00
8605      53.00         179         0.30
8606      54.66         181         0.41
8607      28.24         287         0.08
8608       6.80         365        10.08
8609      10.40         351         1.60
8610       6.84         350         0.81
8611       8.20         370        75.16
8612      81.90          73        16.40
8613      43.00         305        18.50
8614      70.25         111        20.54
8615      26.00         269         0.00
8616      79.20          90        16.10
8617      78.50          89        19.80

[8618 rows x 3 columns]

Selecting only columns which names ends on "(g)":

In [31]:
col_names = food_info.columns.tolist()

gram_columns = []
for el in col_names:
    if el.endswith("(g)"):
        gram_columns.append(el)
print(gram_columns,"\n")

gram_df = food_info[gram_columns]
print(gram_df)

['Water_(g)', 'Protein_(g)', 'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)', 'Sugar_Tot_(g)', 'FA_Sat_(g)', 'FA_Mono_(g)', 'FA_Poly_(g)']

      Water_(g)  Protein_(g)  Lipid_Tot_(g)  Ash_(g)  Carbohydrt_(g)  \
0         15.87         0.85          81.11     2.11            0.06
1         15.87         0.85          81.11     2.11            0.06
2          0.24         0.28          99.48     0.00            0.00
3         42.41        21.40          28.74     5.11            2.34
4         41.11        23.24          29.68     3.18            2.79
5         48.42        20.75          27.68     2.70            0.45
6         51.80        19.80          24.26     3.68            0.46
7         39.28        25.18          29.20     3.28            3.06
8         37.10        24.04          33.82     3.71            1.33
9         37.65        23.37          30.60     3.60            4.78
10        38.20        23.76          32.11     3.36            2.57
11        79.79        11.12           4.30     1.41            3.38
12        79.64        10.69           3.85     1.20            4.61
13        81.01        10.34           0.29     1.71            6.66
14        81.24        10.45           2.27     1.27            4.76
15        82.48        12.39           1.02     1.39            2.72
16        54.44         5.93          34.24     1.32            4.07
17        41.56        24.99          27.80     4.22            1.43
18        55.22        14.21          21.28     5.20            4.09
19        37.92        25.60          31.14     3.79            1.55
20        13.44         9.65          29.51     4.75           42.65
21        41.46        24.94          27.44     3.94            2.22
22        33.19        29.81          32.34     4.30            0.36
23        48.42        20.05          27.25     3.79            0.49
24        41.01        24.48          30.28     3.55            0.68
25        50.01        22.17          22.35     3.28            2.19
26        48.38        21.60          24.64     2.91            2.47
27        53.78        24.26          15.92     3.27            2.77
28        45.54        24.58          19.72     3.80            6.36
29        41.77        23.41          30.04     3.66            1.12
...         ...          ...            ...      ...             ...
8588       2.00         6.60           0.90     2.00           88.60
8589      76.70         1.00           0.20     0.76           21.34
8590      83.10         0.30           0.20     0.29           16.30
8591       1.30         8.70          15.20     1.85           73.40
8592       5.00         7.12           5.46     1.22           81.19
8593       2.80        12.60           9.50     1.71           73.39
8594      81.60         0.50           0.20     0.52           17.18
8595      59.60        28.40           5.10     3.50            3.40
8596      14.50         4.40           7.50     0.80           72.90
8597      49.90        27.50          17.10     2.40            3.10
8598      21.70         0.00          77.80     0.40            0.30
8599       0.00         0.00         100.00     0.00            0.00
8600      23.90         0.00           0.00     0.00           76.10
8601      55.50         4.08          19.50     4.74           16.18
8602       9.00        11.30           2.10    13.90           63.70
8603       4.20         5.30           2.40     9.90           78.20
8604      84.40         0.00           0.00     0.22           15.38
8605      53.00         0.30           0.03     0.08           46.10
8606      54.66         0.41           0.20     0.35           44.38
8607      28.24         0.08           0.01     0.07           71.60
8608       6.80        10.08           3.00     5.70           74.42
8609      10.40         1.60           0.10     1.86           86.04
8610       6.84         0.81           0.90     6.80           84.66
8611       8.20        75.16           1.85     1.00           13.79
8612      81.90        16.40           0.30     1.40            0.00
8613      43.00        18.50          25.10    13.40            0.00
8614      70.25        20.54           0.84     2.97            5.41
8615      26.00         0.00           0.00     0.86           73.14
8616      79.20        16.10           1.40     1.30            2.00
8617      78.50        19.80           0.50     1.20            0.00

      Fiber_TD_(g)  Sugar_Tot_(g)  FA_Sat_(g)  FA_Mono_(g)  FA_Poly_(g)
0              0.0           0.06      51.368       21.021        3.043
1              0.0           0.06      50.489       23.426        3.012
2              0.0           0.00      61.924       28.732        3.694
3              0.0           0.50      18.669        7.778        0.800
4              0.0           0.51      18.764        8.598        0.784
5              0.0           0.45      17.410        8.013        0.826
6              0.0           0.46      15.259        7.023        0.724
7              0.0            NaN      18.584        8.275        0.830
8              0.0           0.28      19.368        8.428        1.433
9              0.0            NaN      19.475        8.671        0.870
10             0.0           0.52      20.218        9.280        0.953
11             0.0           2.67       1.718        0.778        0.123
12             0.2           2.38       2.311        1.036        0.124
13             0.0           1.85       0.169        0.079        0.003
14             0.0           4.00       1.235        0.516        0.083
15             0.0           2.72       0.645        0.291        0.031
16             0.0           3.21      19.292        8.620        1.437
17             0.0           1.43      17.572        8.125        0.665
18             0.0           4.09      14.946        4.623        0.591
19             0.0           1.55      19.196        8.687        1.654
20             0.0            NaN      19.160        7.879        0.938
21             0.0           2.22      17.614        7.747        0.657
22             0.0           0.36      18.913       10.043        1.733
23             0.0           0.49      16.746        8.606        0.495
24             0.0           0.50      19.066        8.751        0.899
25             0.0           1.03      13.152        6.573        0.765
26             0.0           1.01      15.561        7.027        0.778
27             0.0           1.13      10.114        4.510        0.472
28             0.0           2.24      11.473        5.104        0.861
29             0.0           1.12      19.113        8.711        0.661
...            ...            ...         ...          ...          ...
8588           2.6           1.35       0.185        0.252        0.231
8589           1.6          11.36       0.072        0.028        0.041
8590           1.0          14.66       0.058        0.018        0.047
8591           5.7           0.53       2.837        6.341        5.024
8592           4.2          19.79       0.600        2.831        1.307
8593          14.2           0.54       1.415        4.085        3.572
8594           2.0          14.87       0.030        0.025        0.068
8595           0.0           1.33       3.304        1.351        0.180
8596           2.1          35.10       1.500        5.000        0.900
8597           0.0           1.23      10.867        4.844        0.509
8598           0.0           0.30      10.784       18.026       45.539
8599           0.0           0.00      14.367       48.033       33.033
8600           0.1          76.00       0.000        0.000        0.000
8601           0.0           8.21       7.996        3.108        7.536
8602          27.8          35.90       0.555        0.405        1.035
8603           6.1           0.70       0.984        1.154        0.131
8604           0.1            NaN       0.000        0.000        0.000
8605           0.8          45.30       0.009        0.001        0.008
8606           2.6          37.75       0.000        0.000        0.000
8607           0.0          24.53       0.003        0.001        0.009
8608          10.1           0.70       1.578        1.150        0.130
8609           0.9           2.90       0.018        0.032        0.050
8610           0.8           0.90       0.099        0.116        0.433
8611           0.6           0.00       0.272        0.156        0.810
8612           0.0           0.00       0.076        0.053        0.102
8613           0.0           0.00       7.148        8.320        6.210
8614           0.0           0.00       0.218        0.082        0.222
8615           0.0          73.20       0.000        0.000        0.000
8616           0.0           0.00       0.361        0.259        0.252
8617           0.0           0.00       0.127        0.088        0.170

[8618 rows x 10 columns]

# Data Manipulation with pandas

Using panda with calculation

In [33]:
add_100 = food_info["Carbohydrt_(g)"] + 100
add_100

0       100.06
1       100.06
2       100.00
3       102.34
4       102.79
5       100.45
6       100.46
7       103.06
8       101.33
9       104.78
10      102.57
11      103.38
12      104.61
13      106.66
14      104.76
15      102.72
16      104.07
17      101.43
18      104.09
19      101.55
20      142.65
21      102.22
22      100.36
23      100.49
24      100.68
25      102.19
26      102.47
27      102.77
28      106.36
29      101.12
         ...
8588    188.60
8589    121.34
8590    116.30
8591    173.40
8592    181.19
8593    173.39
8594    117.18
8595    103.40
8596    172.90
8597    103.10
8598    100.30
8599    100.00
8600    176.10
8601    116.18
8602    163.70
8603    178.20
8604    115.38
8605    146.10
8606    144.38
8607    171.60
8608    174.42
8609    186.04
8610    184.66
8611    113.79
8612    100.00
8613    100.00
8614    105.41
8615    173.14
8616    102.00
8617    100.00
Name: Carbohydrt_(g), dtype: float64

In [34]:
water_energy = food_info["Water_(g)"] * food_info["Energ_Kcal"]
water_energy

0       11378.79
1       11378.79
2         210.24
3       14970.73
4       15251.81
5       16172.28
6       15540.00
7       14769.28
8       15062.60
9       14570.55
10      15050.80
11       7819.42
12       7725.08
13       5832.72
14       6580.44
15       5938.56
16      18618.48
17      14836.92
18      14578.08
19      14750.88
20       6263.04
21      14759.76
22      13707.47
23      15833.34
24      15296.73
25      15003.00
26      15384.84
27      13660.12
28      13707.54
29      15371.36
          ...
8588      778.00
8589     6979.70
8590     5650.80
8591      604.50
8592     2005.00
8593     1201.20
8594     5956.80
8595    10668.40
8596     5466.50
8597    13972.00
8598    14929.60
8599        0.00
8600     6668.10
8601    14263.50
8602     2871.00
8603     1495.20
8604     5232.80
8605     9487.00
8606     9893.46
8607     8104.88
8608     2482.00
8609     3650.40
8610     2394.00
8611     3034.00
8612     5978.70
8613    13115.00
8614     7797.75
8615     6994.00
8616     7128.00
8617     6986.50
dtype: float64

Adding new column in data frame:

In [40]:
food_info["water_energy"] = water_energy
food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),water_energy
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0,11378.79
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0,11378.79
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0,210.24
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0,14970.73
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0,15251.81

In [41]:
del food_info["water_energy"]
food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,721.0,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,1080.0,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0

Sorting values

In [44]:
food_info.sort_values("Energ_Kcal", inplace=True, ascending=False)
food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
610,4001,FAT BEEF TALLOW,0.0,902,0.0,100.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.7,0.7,28.0,0.0,49.800,41.800,4.000,109.0
704,4592,FISH OIL MENHADEN FULLY HYDR,0.0,902,0.0,100.0,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,95.600,0.000,0.000,500.0
611,4002,LARD,0.0,902,0.0,100.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.6,2.5,102.0,0.0,39.200,45.100,11.200,95.0
706,4594,FISH OIL SARDINE,0.0,902,0.0,100.0,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,8.3,332.0,NaN,29.892,33.841,31.867,710.0
705,4593,FISH OIL SALMON,0.0,902,0.0,100.0,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,19.872,29.037,40.324,485.0